### ISSUE TITLE
`class:` and `class-` shorthands are not stripping `class` prefix

### ISSUE THREAD

**Issue by jquesada2016** [gbj/leptos#52] opened 2022-11-06 03:22 UTC
Writting the following:

```rust
view! { cx,
  <div class:hidden=true />
}
```

results in
```html
<div class="class:hidden" ></div>
```

Same for the `class-` variant.

**Comment by gbj** [comment] 2022-11-06 03:25
Thanks, this is a bug I introduced earlier this week and just caught today and it should be fixed on then,sin branch and in the latest release. Do you know what version you're using?

**Comment by jquesada2016** [comment] 2022-11-06 03:25
0.0.12

**Comment by jquesada2016** [comment] 2022-11-06 03:27
I hadn't checked there was a new release before creating the issue, will do next time! I keep forgetting the crate is moving fast!

**Comment by gbj** [comment] 2022-11-06 03:28
Yeah no problem. I literally released the new version (okay, several new versions because I screwed a couple things up...) in the last thirty minutes so we just overlapped... This is why I'm staying on 0.0.x for now :-)

Thanks for catching this and letting me know. I'll close the issue, but feel free to reopen if the problem is fixed.

**Closed by gbj** 2022-11-06 03:28 UTC
